"""Derived observability read models over canonical workflow evidence.

Inspect and replay are readers, not alternate authorities.
They must expose completeness and watermark metadata whenever they summarize state.
"""

from .read_models import (
    DerivedReadModel,
    GraphLineageReadModel,
    GraphTopologyEdge,
    GraphTopologyNode,
    GraphTopologyReadModel,
    InspectionReadModel,
    OperatorFrameReadModel,
    ProjectionCompleteness,
    ProjectionWatermark,
    ReplayReadModel,
)
from .graph_lineage import graph_lineage_run
from .graph_topology import graph_topology_run
from .operator_dashboard import (
    NativeOperatorCockpitDispatchReadModel,
    NativeOperatorCockpitError,
    NativeOperatorCockpitFailoverEffectiveSliceReadModel,
    NativeOperatorCockpitFailoverReadModel,
    NativeOperatorCockpitFailoverSelectorContract,
    NativeOperatorCockpitProvenance,
    NativeOperatorCockpitReadModel,
    NativeOperatorCockpitRouteReadModel,
    NativeOperatorStatusReadModel,
    NativeOperatorSupportSnapshot,
    load_native_operator_support,
    operator_cockpit_run,
    operator_cockpit_run_with_failover_contract,
    operator_status_run,
    render_operator_cockpit,
    render_operator_status,
)
from .operator_topology import (
    NativeCutoverGraphBindingStatus,
    NativeCutoverGraphGateStatus,
    NativeCutoverGraphStatusReadModel,
    NativeCutoverReceiptSnapshot,
    NativeCutoverScoreboardReadModel,
    NativeCutoverStatusSnapshot,
    OperatorGraphBugRecord,
    OperatorGraphEdge,
    OperatorGraphFreshness,
    OperatorGraphNode,
    OperatorGraphProjectionError,
    OperatorGraphReadModel,
    OperatorGraphRoadmapRecord,
    cutover_graph_status_run,
    cutover_scoreboard_run,
    load_operator_graph_projection,
    render_cutover_graph_status,
    render_cutover_scoreboard,
)
from .status_observability import (
    FrontdoorContractDriftIssue,
    FrontdoorContractDriftReadModel,
    FrontdoorFailureTaxonomyReadModel,
    FrontdoorObservabilityAnomalyDigest,
    FrontdoorObservabilityReadModel,
    FrontdoorProvenanceCoverageReadModel,
    FrontdoorProvenanceCoverageSection,
    FrontdoorRunIdentityReadModel,
    build_frontdoor_observability,
    render_frontdoor_observability,
)
from .readers import inspect_run, replay_run

__all__ = [
    "DerivedReadModel",
    "NativeCutoverReceiptSnapshot",
    "NativeCutoverScoreboardReadModel",
    "NativeCutoverStatusSnapshot",
    "NativeCutoverGraphBindingStatus",
    "NativeCutoverGraphGateStatus",
    "NativeCutoverGraphStatusReadModel",
    "OperatorGraphBugRecord",
    "OperatorGraphEdge",
    "OperatorGraphFreshness",
    "OperatorGraphNode",
    "OperatorGraphProjectionError",
    "OperatorGraphReadModel",
    "OperatorGraphRoadmapRecord",
    "GraphLineageReadModel",
    "GraphTopologyEdge",
    "GraphTopologyNode",
    "GraphTopologyReadModel",
    "graph_lineage_run",
    "graph_topology_run",
    "InspectionReadModel",
    "OperatorFrameReadModel",
    "FrontdoorContractDriftIssue",
    "FrontdoorContractDriftReadModel",
    "FrontdoorFailureTaxonomyReadModel",
    "FrontdoorObservabilityAnomalyDigest",
    "FrontdoorObservabilityReadModel",
    "FrontdoorProvenanceCoverageReadModel",
    "FrontdoorProvenanceCoverageSection",
    "FrontdoorRunIdentityReadModel",
    "build_frontdoor_observability",
    "render_frontdoor_observability",
    "cutover_graph_status_run",
    "load_operator_graph_projection",
    "cutover_scoreboard_run",
    "NativeOperatorCockpitDispatchReadModel",
    "NativeOperatorCockpitError",
    "NativeOperatorCockpitFailoverEffectiveSliceReadModel",
    "NativeOperatorCockpitFailoverReadModel",
    "NativeOperatorCockpitFailoverSelectorContract",
    "NativeOperatorCockpitProvenance",
    "NativeOperatorCockpitReadModel",
    "NativeOperatorCockpitRouteReadModel",
    "operator_cockpit_run",
    "operator_cockpit_run_with_failover_contract",
    "NativeOperatorStatusReadModel",
    "NativeOperatorSupportSnapshot",
    "load_native_operator_support",
    "ProjectionCompleteness",
    "ProjectionWatermark",
    "operator_status_run",
    "render_cutover_graph_status",
    "render_cutover_scoreboard",
    "render_operator_cockpit",
    "ReplayReadModel",
    "render_operator_status",
    "inspect_run",
    "replay_run",
]
