"""Sealed SubsystemsContract protocol for handler dependencies.

Handlers depend on a stable subset of subsystems. Instead of accepting a
whole ``_BaseSubsystems`` instance (which has lazy-loaded internals),
they should accept something that satisfies ``SubsystemsContract``.

``_BaseSubsystems`` structurally satisfies this protocol — no runtime
changes are required at the implementation site, but new handlers gain
typed IDE support and an explicit list of what they actually use.

Roadmap: ``roadmap_item.replace.basesubsystems.god.object.with.a.sealed.subsystemscontract.protocol``
"""

from __future__ import annotations

from types import ModuleType
from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class SubsystemsContract(Protocol):
    """Declared subsystem surface that handlers depend on.

    Every handler acquiring a subsystem should go through this contract
    (or a narrower contract derived from it). The underlying ``_BaseSubsystems``
    class implements every method structurally.

    Return types are intentionally ``Any`` to avoid import cycles at the
    contract boundary — the concrete classes live inside ``runtime.*`` and
    ``memory.*`` and are lazy-loaded on first call.
    """

    # ---- database -------------------------------------------------------
    def get_pg_conn(self) -> Any: ...

    # ---- observability --------------------------------------------------
    def get_obs_hub(self) -> Any: ...
    def get_receipt_ingester(self) -> Any: ...
    def get_quality_materializer(self) -> Any: ...
    def get_quality_views_mod(self) -> ModuleType: ...

    # ---- bugs / operator panel -----------------------------------------
    def get_bug_tracker(self) -> Any: ...
    def get_bug_tracker_mod(self) -> ModuleType: ...
    def get_operator_panel(self) -> Any: ...
    def get_operator_panel_mod(self) -> ModuleType: ...

    # ---- memory / knowledge --------------------------------------------
    def get_knowledge_graph(self) -> Any: ...
    def get_memory_engine(self) -> Any: ...
    def get_intent_matcher(self) -> Any: ...
    def get_module_indexer(self) -> Any: ...
    def get_embedding_service(self) -> Any | None: ...

    # ---- orchestration --------------------------------------------------
    def get_staleness_detector(self) -> Any: ...
    def get_wave_orchestrator(self) -> Any: ...
    def get_wave_orchestrator_mod(self) -> ModuleType: ...
    def get_self_healer(self) -> Any: ...
    def get_heartbeat_runner(self) -> Any: ...
    def get_session_carry_mgr(self) -> Any: ...

    # ---- policy / governance -------------------------------------------
    def get_constraint_ledger(self) -> Any: ...
    def get_constraint_miner(self) -> Any: ...
    def get_friction_ledger(self) -> Any: ...
    def get_governance_filter(self) -> Any: ...

    # ---- artifacts / manifests -----------------------------------------
    def get_artifact_store(self) -> Any: ...
    def get_manifest_generator(self) -> Any: ...

    # ---- notifications / health -----------------------------------------
    def get_notification_consumer(self) -> Any: ...
    def drain_notifications(self) -> str: ...
    def get_health_mod(self) -> ModuleType: ...


__all__ = ["SubsystemsContract"]
