-- Migration 049: route policy registry
--
-- Runtime routing weights and penalty policy are long-term authority, not
-- Python constants. The router reads this table to decide how to balance
-- task rank, route health, cost, benchmark trust, claim balancing, and
-- downstream review penalties.

BEGIN;

CREATE TABLE IF NOT EXISTS route_policy_registry (
    route_policy_key TEXT PRIMARY KEY,
    task_rank_weight DOUBLE PRECISION NOT NULL,
    route_health_weight DOUBLE PRECISION NOT NULL,
    cost_weight DOUBLE PRECISION NOT NULL,
    benchmark_weight DOUBLE PRECISION NOT NULL,
    prefer_cost_task_rank_weight DOUBLE PRECISION NOT NULL,
    prefer_cost_route_health_weight DOUBLE PRECISION NOT NULL,
    prefer_cost_cost_weight DOUBLE PRECISION NOT NULL,
    prefer_cost_benchmark_weight DOUBLE PRECISION NOT NULL,
    claim_route_health_weight DOUBLE PRECISION NOT NULL,
    claim_rank_weight DOUBLE PRECISION NOT NULL,
    claim_load_weight DOUBLE PRECISION NOT NULL,
    claim_internal_failure_penalty_step DOUBLE PRECISION NOT NULL,
    claim_priority_penalty_step DOUBLE PRECISION NOT NULL,
    neutral_benchmark_score DOUBLE PRECISION NOT NULL,
    mixed_benchmark_score DOUBLE PRECISION NOT NULL,
    neutral_route_health DOUBLE PRECISION NOT NULL,
    min_route_health DOUBLE PRECISION NOT NULL,
    max_route_health DOUBLE PRECISION NOT NULL,
    success_health_bump DOUBLE PRECISION NOT NULL,
    review_success_bump DOUBLE PRECISION NOT NULL,
    consecutive_failure_penalty_step DOUBLE PRECISION NOT NULL,
    consecutive_failure_penalty_cap DOUBLE PRECISION NOT NULL,
    internal_failure_penalties JSONB NOT NULL DEFAULT '{}'::jsonb,
    review_severity_penalties JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO route_policy_registry (
    route_policy_key,
    task_rank_weight,
    route_health_weight,
    cost_weight,
    benchmark_weight,
    prefer_cost_task_rank_weight,
    prefer_cost_route_health_weight,
    prefer_cost_cost_weight,
    prefer_cost_benchmark_weight,
    claim_route_health_weight,
    claim_rank_weight,
    claim_load_weight,
    claim_internal_failure_penalty_step,
    claim_priority_penalty_step,
    neutral_benchmark_score,
    mixed_benchmark_score,
    neutral_route_health,
    min_route_health,
    max_route_health,
    success_health_bump,
    review_success_bump,
    consecutive_failure_penalty_step,
    consecutive_failure_penalty_cap,
    internal_failure_penalties,
    review_severity_penalties
) VALUES (
    'task_type_router.default',
    0.35,
    0.40,
    0.10,
    0.15,
    0.25,
    0.35,
    0.30,
    0.10,
    0.55,
    0.30,
    0.15,
    0.08,
    0.01,
    0.50,
    0.55,
    0.65,
    0.05,
    1.0,
    0.04,
    0.02,
    0.08,
    0.20,
    '{"verification_failed": 0.25, "context_overflow": 0.18, "parse_error": 0.15, "sandbox_error": 0.12, "scope_violation": 0.05, "unknown": 0.10}'::jsonb,
    '{"high": 0.15, "medium": 0.08, "low": 0.03}'::jsonb
)
ON CONFLICT (route_policy_key) DO UPDATE SET
    task_rank_weight = EXCLUDED.task_rank_weight,
    route_health_weight = EXCLUDED.route_health_weight,
    cost_weight = EXCLUDED.cost_weight,
    benchmark_weight = EXCLUDED.benchmark_weight,
    prefer_cost_task_rank_weight = EXCLUDED.prefer_cost_task_rank_weight,
    prefer_cost_route_health_weight = EXCLUDED.prefer_cost_route_health_weight,
    prefer_cost_cost_weight = EXCLUDED.prefer_cost_cost_weight,
    prefer_cost_benchmark_weight = EXCLUDED.prefer_cost_benchmark_weight,
    claim_route_health_weight = EXCLUDED.claim_route_health_weight,
    claim_rank_weight = EXCLUDED.claim_rank_weight,
    claim_load_weight = EXCLUDED.claim_load_weight,
    claim_internal_failure_penalty_step = EXCLUDED.claim_internal_failure_penalty_step,
    claim_priority_penalty_step = EXCLUDED.claim_priority_penalty_step,
    neutral_benchmark_score = EXCLUDED.neutral_benchmark_score,
    mixed_benchmark_score = EXCLUDED.mixed_benchmark_score,
    neutral_route_health = EXCLUDED.neutral_route_health,
    min_route_health = EXCLUDED.min_route_health,
    max_route_health = EXCLUDED.max_route_health,
    success_health_bump = EXCLUDED.success_health_bump,
    review_success_bump = EXCLUDED.review_success_bump,
    consecutive_failure_penalty_step = EXCLUDED.consecutive_failure_penalty_step,
    consecutive_failure_penalty_cap = EXCLUDED.consecutive_failure_penalty_cap,
    internal_failure_penalties = EXCLUDED.internal_failure_penalties,
    review_severity_penalties = EXCLUDED.review_severity_penalties,
    updated_at = now();

COMMIT;
