BEGIN;

CREATE TABLE IF NOT EXISTS surface_catalog_registry (
    catalog_item_id TEXT PRIMARY KEY,
    surface_name TEXT NOT NULL,
    label TEXT NOT NULL,
    icon TEXT NOT NULL,
    family TEXT NOT NULL CHECK (family IN ('trigger', 'gather', 'think', 'act', 'control')),
    status TEXT NOT NULL CHECK (status IN ('ready', 'coming_soon')),
    drop_kind TEXT NOT NULL CHECK (drop_kind IN ('node', 'edge')),
    action_value TEXT,
    gate_family TEXT,
    description TEXT NOT NULL DEFAULT '',
    truth_category TEXT NOT NULL CHECK (truth_category IN ('runtime', 'persisted', 'alias', 'partial', 'coming_soon')),
    truth_badge TEXT NOT NULL,
    truth_detail TEXT NOT NULL,
    surface_tier TEXT NOT NULL CHECK (surface_tier IN ('primary', 'advanced', 'hidden')),
    surface_badge TEXT NOT NULL,
    surface_detail TEXT NOT NULL,
    hard_choice TEXT,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INTEGER NOT NULL DEFAULT 0,
    binding_revision TEXT NOT NULL,
    decision_ref TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT surface_catalog_registry_drop_kind_binding_check
        CHECK (
            (drop_kind = 'node' AND action_value IS NOT NULL AND gate_family IS NULL)
            OR (drop_kind = 'edge' AND gate_family IS NOT NULL AND action_value IS NULL)
        )
);

CREATE INDEX IF NOT EXISTS surface_catalog_registry_surface_enabled_order_idx
    ON surface_catalog_registry (surface_name, enabled, display_order, catalog_item_id);

CREATE INDEX IF NOT EXISTS surface_catalog_registry_surface_tier_idx
    ON surface_catalog_registry (surface_name, surface_tier, drop_kind);

COMMENT ON TABLE surface_catalog_registry IS 'Canonical builder surface catalog registry. Moon primitives and their truth/surface policy live here instead of hardcoded surface lists.';
COMMENT ON COLUMN surface_catalog_registry.binding_revision IS 'Revision stamp for the seeded surface-catalog binding. Changes must publish a new revision.';
COMMENT ON COLUMN surface_catalog_registry.decision_ref IS 'Decision authority that justified the current surface-catalog row.';

INSERT INTO surface_catalog_registry (
    catalog_item_id,
    surface_name,
    label,
    icon,
    family,
    status,
    drop_kind,
    action_value,
    gate_family,
    description,
    truth_category,
    truth_badge,
    truth_detail,
    surface_tier,
    surface_badge,
    surface_detail,
    hard_choice,
    enabled,
    display_order,
    binding_revision,
    decision_ref
) VALUES
    (
        'trigger-manual',
        'moon',
        'Manual',
        'trigger',
        'trigger',
        'ready',
        'node',
        'trigger',
        NULL,
        'User-initiated run',
        'runtime',
        'Runs on release',
        'Creates trigger intent that is preserved into compiled triggers.',
        'primary',
        'Core now',
        'Primary trigger primitive with real compile and release authority.',
        NULL,
        TRUE,
        10,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'trigger-webhook',
        'moon',
        'Webhook',
        'tool',
        'trigger',
        'ready',
        'node',
        'trigger/webhook',
        NULL,
        'Inbound webhook with HMAC verification',
        'runtime',
        'Runs on release',
        'Creates trigger intent that is preserved into compiled triggers.',
        'primary',
        'Core now',
        'Primary trigger primitive with real compile and release authority.',
        NULL,
        TRUE,
        20,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'trigger-schedule',
        'moon',
        'Schedule',
        'trigger',
        'trigger',
        'ready',
        'node',
        'trigger/schedule',
        NULL,
        'Cron or interval trigger',
        'runtime',
        'Runs on release',
        'Creates trigger intent that is preserved into compiled triggers.',
        'primary',
        'Core now',
        'Primary trigger primitive with real compile and release authority.',
        NULL,
        TRUE,
        30,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'gather-research',
        'moon',
        'Web Research',
        'research',
        'gather',
        'ready',
        'node',
        'auto/research',
        NULL,
        'Search and analyze web sources',
        'runtime',
        'Runs on release',
        'Persists into the build graph and becomes a planned runtime route at release.',
        'primary',
        'Core now',
        'Primary Moon step primitive with a real planned runtime route.',
        NULL,
        TRUE,
        40,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'gather-docs',
        'moon',
        'Docs',
        'research',
        'gather',
        'ready',
        'node',
        'auto/research',
        NULL,
        'Read and extract from documents',
        'alias',
        'Alias',
        'Uses the same `auto/research` route as Web Research today.',
        'hidden',
        'Merged',
        'Merged into Web Research because both buttons point at the same route today.',
        'Merged into Web Research. One route gets one obvious button.',
        TRUE,
        50,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'think-classify',
        'moon',
        'Classify',
        'classify',
        'think',
        'ready',
        'node',
        'auto/classify',
        NULL,
        'Score, triage, or categorize',
        'runtime',
        'Runs on release',
        'Uses the analysis lane backed by task_type_route_profiles and task_type_routing authority.',
        'primary',
        'Core now',
        'Backed by a real analysis lane instead of borrowing the support route.',
        NULL,
        TRUE,
        60,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'think-draft',
        'moon',
        'Draft',
        'draft',
        'think',
        'ready',
        'node',
        'auto/draft',
        NULL,
        'Generate or compose content',
        'runtime',
        'Runs on release',
        'Persists into the build graph and becomes a planned runtime route at release.',
        'primary',
        'Core now',
        'Primary Moon step primitive with a real planned runtime route.',
        NULL,
        TRUE,
        70,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'think-fan-out',
        'moon',
        'Fan Out',
        'classify',
        'think',
        'ready',
        'node',
        'workflow.fanout',
        NULL,
        'Split into parallel sub-tasks and aggregate',
        'runtime',
        'Runs on release',
        'Fan-out now has a verified runtime lane and compiles into the same release path as other core step routes.',
        'primary',
        'Core now',
        'Fan-out now has a verified runtime lane, so Moon can surface it as a core builder primitive.',
        NULL,
        TRUE,
        80,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'think-fan-out-legacy',
        'moon',
        'Fan Out (Legacy)',
        'classify',
        'think',
        'ready',
        'node',
        'auto/fan-out',
        NULL,
        'Legacy fan-out token kept for older saved graphs',
        'alias',
        'Alias',
        'Legacy fan-out token kept for existing saved graphs; Moon uses `workflow.fanout` now.',
        'hidden',
        'Alias',
        'Legacy token only, kept so older graphs still open cleanly.',
        'Compatibility alias for saved graphs only.',
        TRUE,
        90,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'act-notify',
        'moon',
        'Notify',
        'notify',
        'act',
        'ready',
        'node',
        '@notifications/send',
        NULL,
        'Send notification (Slack, email, etc.)',
        'runtime',
        'Runs on release',
        'Persists into the build graph and becomes a planned runtime route at release.',
        'primary',
        'Core now',
        'Real action primitive with a stable property surface in the node inspector.',
        NULL,
        TRUE,
        100,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'act-webhook-out',
        'moon',
        'HTTP Request',
        'tool',
        'act',
        'ready',
        'node',
        '@webhook/post',
        NULL,
        'Call an external webhook or API',
        'runtime',
        'Runs on release',
        'Persists into the build graph and becomes a planned runtime route at release.',
        'primary',
        'Core now',
        'Visible now that Moon offers opinionated request presets instead of a blank transport form.',
        NULL,
        TRUE,
        110,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'act-invoke',
        'moon',
        'Run Workflow',
        'tool',
        'act',
        'ready',
        'node',
        '@workflow/invoke',
        NULL,
        'Invoke another workflow as a sub-workflow',
        'runtime',
        'Runs on release',
        'Persists into the build graph and becomes a planned runtime route at release.',
        'primary',
        'Core now',
        'Visible now that Moon can pick saved child workflows by name from the inspector.',
        NULL,
        TRUE,
        120,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'ctrl-approval',
        'moon',
        'Approval',
        'gate',
        'control',
        'ready',
        'edge',
        NULL,
        'approval',
        'Human approval gate',
        'runtime',
        'Executes',
        'Compiled into dependency edges that change runtime flow today.',
        'primary',
        'Core now',
        'Pauses the downstream step behind a human approval checkpoint before execution continues.',
        NULL,
        TRUE,
        130,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'ctrl-review',
        'moon',
        'Human Review',
        'review',
        'control',
        'ready',
        'edge',
        NULL,
        'human_review',
        'Manual review before proceeding',
        'persisted',
        'Saved only',
        'Stored in edge metadata now, but not enforced by the planner yet.',
        'hidden',
        'Removed',
        'Folded into Approval so Moon keeps one obvious human gate concept.',
        'Collapsed into Approval. Two human gate names for one future concept would be noise.',
        TRUE,
        140,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'ctrl-validation',
        'moon',
        'Validation',
        'gate',
        'control',
        'ready',
        'edge',
        NULL,
        'validation',
        'Automated verification command gate',
        'runtime',
        'Executes',
        'Runs the configured verification command before the downstream step can continue.',
        'primary',
        'Core now',
        'Executes the configured verification command before the downstream step proceeds.',
        NULL,
        TRUE,
        150,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'ctrl-branch',
        'moon',
        'Branch',
        'gate',
        'control',
        'ready',
        'edge',
        NULL,
        'conditional',
        'Conditional path (equals, in, not_equals, not_in)',
        'runtime',
        'Executes',
        'Compiled into dependency edges that change runtime flow today.',
        'primary',
        'Core now',
        'This is one of the few gate types that changes execution today.',
        NULL,
        TRUE,
        160,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'ctrl-retry',
        'moon',
        'Retry',
        'gate',
        'control',
        'ready',
        'edge',
        NULL,
        'retry',
        'Retry with backoff + provider failover chain',
        'runtime',
        'Executes',
        'Sets the downstream job''s max_attempts so failed work can requeue through the runtime retry loop.',
        'advanced',
        'Later',
        'Feeds retry policy into downstream job max_attempts, but stays outside the core gate set.',
        NULL,
        TRUE,
        170,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    ),
    (
        'ctrl-on-failure',
        'moon',
        'On Failure',
        'gate',
        'control',
        'ready',
        'edge',
        NULL,
        'after_failure',
        'Run only if upstream step failed',
        'runtime',
        'Executes',
        'Compiled into dependency edges that change runtime flow today.',
        'primary',
        'Core now',
        'This is one of the few gate types that changes execution today.',
        NULL,
        TRUE,
        180,
        'binding.surface_catalog_registry.moon.bootstrap.20260415',
        'decision.surface_catalog_registry.moon.bootstrap.20260415'
    )
ON CONFLICT (catalog_item_id) DO UPDATE SET
    surface_name = EXCLUDED.surface_name,
    label = EXCLUDED.label,
    icon = EXCLUDED.icon,
    family = EXCLUDED.family,
    status = EXCLUDED.status,
    drop_kind = EXCLUDED.drop_kind,
    action_value = EXCLUDED.action_value,
    gate_family = EXCLUDED.gate_family,
    description = EXCLUDED.description,
    truth_category = EXCLUDED.truth_category,
    truth_badge = EXCLUDED.truth_badge,
    truth_detail = EXCLUDED.truth_detail,
    surface_tier = EXCLUDED.surface_tier,
    surface_badge = EXCLUDED.surface_badge,
    surface_detail = EXCLUDED.surface_detail,
    hard_choice = EXCLUDED.hard_choice,
    enabled = EXCLUDED.enabled,
    display_order = EXCLUDED.display_order,
    binding_revision = EXCLUDED.binding_revision,
    decision_ref = EXCLUDED.decision_ref,
    updated_at = now();

COMMIT;
