-- Migration 145: Operation Catalog Object Schema Bindings
-- Admit object schema reads and writes into the operation catalog.

INSERT INTO operation_catalog_registry (
    operation_ref,
    operation_name,
    source_kind,
    operation_kind,
    http_method,
    http_path,
    input_model_ref,
    handler_ref,
    authority_ref,
    projection_ref,
    posture,
    idempotency_policy,
    enabled,
    binding_revision,
    decision_ref
)
VALUES
    (
        'object-schema-type-list',
        'object_schema.type_list',
        'operation_query',
        'query',
        'GET',
        '/api/object-types',
        'runtime.operations.queries.object_schema.QueryObjectTypes',
        'runtime.operations.queries.object_schema.handle_query_object_types',
        'authority.object_schema',
        'projection.object_schema',
        NULL,
        NULL,
        true,
        'binding.operation_catalog_registry.object_schema_bindings.20260417',
        'decision.operation_catalog_registry.object_schema_bindings.20260417'
    ),
    (
        'object-schema-type-get',
        'object_schema.type_get',
        'operation_query',
        'query',
        'GET',
        '/api/object-types/{type_id}',
        'runtime.operations.queries.object_schema.QueryObjectType',
        'runtime.operations.queries.object_schema.handle_query_object_type',
        'authority.object_schema',
        'projection.object_schema',
        NULL,
        NULL,
        true,
        'binding.operation_catalog_registry.object_schema_bindings.20260417',
        'decision.operation_catalog_registry.object_schema_bindings.20260417'
    ),
    (
        'object-schema-type-upsert-post',
        'object_schema.type_upsert',
        'operation_command',
        'command',
        'POST',
        '/api/object-types',
        'runtime.operations.commands.object_schema.UpsertObjectTypeCommand',
        'runtime.operations.commands.object_schema.handle_upsert_object_type',
        'authority.object_schema',
        NULL,
        NULL,
        NULL,
        true,
        'binding.operation_catalog_registry.object_schema_bindings.20260417',
        'decision.operation_catalog_registry.object_schema_bindings.20260417'
    ),
    (
        'object-schema-type-upsert-put',
        'object_schema.type_upsert_by_id',
        'operation_command',
        'command',
        'PUT',
        '/api/object-types/{type_id}',
        'runtime.operations.commands.object_schema.UpsertObjectTypeCommand',
        'runtime.operations.commands.object_schema.handle_upsert_object_type',
        'authority.object_schema',
        NULL,
        NULL,
        NULL,
        true,
        'binding.operation_catalog_registry.object_schema_bindings.20260417',
        'decision.operation_catalog_registry.object_schema_bindings.20260417'
    ),
    (
        'object-schema-type-delete',
        'object_schema.type_delete',
        'operation_command',
        'command',
        'DELETE',
        '/api/object-types/{type_id}',
        'runtime.operations.commands.object_schema.DeleteObjectTypeCommand',
        'runtime.operations.commands.object_schema.handle_delete_object_type',
        'authority.object_schema',
        NULL,
        NULL,
        NULL,
        true,
        'binding.operation_catalog_registry.object_schema_bindings.20260417',
        'decision.operation_catalog_registry.object_schema_bindings.20260417'
    ),
    (
        'object-schema-field-list',
        'object_schema.field_list',
        'operation_query',
        'query',
        'GET',
        '/api/object-types/{type_id}/fields',
        'runtime.operations.queries.object_schema.QueryObjectFields',
        'runtime.operations.queries.object_schema.handle_query_object_fields',
        'authority.object_schema',
        'projection.object_schema',
        NULL,
        NULL,
        true,
        'binding.operation_catalog_registry.object_schema_bindings.20260417',
        'decision.operation_catalog_registry.object_schema_bindings.20260417'
    ),
    (
        'object-schema-field-upsert',
        'object_schema.field_upsert',
        'operation_command',
        'command',
        'POST',
        '/api/object-types/{type_id}/fields',
        'runtime.operations.commands.object_schema.UpsertObjectFieldCommand',
        'runtime.operations.commands.object_schema.handle_upsert_object_field',
        'authority.object_schema',
        NULL,
        NULL,
        NULL,
        true,
        'binding.operation_catalog_registry.object_schema_bindings.20260417',
        'decision.operation_catalog_registry.object_schema_bindings.20260417'
    ),
    (
        'object-schema-field-retire',
        'object_schema.field_retire',
        'operation_command',
        'command',
        'DELETE',
        '/api/object-types/{type_id}/fields/{field_name}',
        'runtime.operations.commands.object_schema.RetireObjectFieldCommand',
        'runtime.operations.commands.object_schema.handle_retire_object_field',
        'authority.object_schema',
        NULL,
        NULL,
        NULL,
        true,
        'binding.operation_catalog_registry.object_schema_bindings.20260417',
        'decision.operation_catalog_registry.object_schema_bindings.20260417'
    )
ON CONFLICT (operation_ref) DO UPDATE SET
    operation_name = EXCLUDED.operation_name,
    source_kind = EXCLUDED.source_kind,
    operation_kind = EXCLUDED.operation_kind,
    http_method = EXCLUDED.http_method,
    http_path = EXCLUDED.http_path,
    input_model_ref = EXCLUDED.input_model_ref,
    handler_ref = EXCLUDED.handler_ref,
    authority_ref = EXCLUDED.authority_ref,
    projection_ref = EXCLUDED.projection_ref,
    posture = EXCLUDED.posture,
    idempotency_policy = EXCLUDED.idempotency_policy,
    enabled = EXCLUDED.enabled,
    binding_revision = EXCLUDED.binding_revision,
    decision_ref = EXCLUDED.decision_ref;
