BEGIN;

INSERT INTO operation_catalog_registry (
    operation_ref,
    operation_name,
    source_kind,
    operation_kind,
    http_method,
    http_path,
    input_model_ref,
    handler_ref,
    authority_ref,
    projection_ref,
    posture,
    idempotency_policy,
    enabled,
    binding_revision,
    decision_ref
)
VALUES
    (
        'operator-architecture-policy-record',
        'operator.architecture_policy_record',
        'operation_command',
        'command',
        'POST',
        '/api/operator/architecture-policy',
        'runtime.operations.commands.operator_control.ArchitecturePolicyRecordCommand',
        'runtime.operations.commands.operator_control.handle_architecture_policy_record',
        'authority.operator_decisions',
        NULL,
        NULL,
        NULL,
        TRUE,
        'binding.operation_catalog_registry.operator_finish.20260417',
        'decision.operation_catalog_registry.operator_finish.20260417'
    ),
    (
        'operator-functional-area-record',
        'operator.functional_area_record',
        'operation_command',
        'command',
        'POST',
        '/api/operator/functional-area',
        'runtime.operations.commands.operator_control.FunctionalAreaRecordCommand',
        'runtime.operations.commands.operator_control.handle_functional_area_record',
        'authority.functional_areas',
        NULL,
        NULL,
        NULL,
        TRUE,
        'binding.operation_catalog_registry.operator_finish.20260417',
        'decision.operation_catalog_registry.operator_finish.20260417'
    ),
    (
        'operator-object-relation-record',
        'operator.object_relation_record',
        'operation_command',
        'command',
        'POST',
        '/api/operator/object-relation',
        'runtime.operations.commands.operator_control.OperatorObjectRelationRecordCommand',
        'runtime.operations.commands.operator_control.handle_operator_object_relation_record',
        'authority.operator_object_relations',
        NULL,
        NULL,
        NULL,
        TRUE,
        'binding.operation_catalog_registry.operator_finish.20260417',
        'decision.operation_catalog_registry.operator_finish.20260417'
    ),
    (
        'operator-circuit-states',
        'operator.circuit_states',
        'operation_query',
        'query',
        'GET',
        '/api/circuits',
        'runtime.operations.queries.circuits.QueryCircuitStates',
        'runtime.operations.queries.circuits.handle_query_circuit_states',
        'authority.circuit_breakers',
        'projection.circuit_breakers',
        NULL,
        NULL,
        TRUE,
        'binding.operation_catalog_registry.operator_finish.20260417',
        'decision.operation_catalog_registry.operator_finish.20260417'
    ),
    (
        'operator-circuit-history',
        'operator.circuit_history',
        'operation_query',
        'query',
        'GET',
        '/api/circuits/history',
        'runtime.operations.queries.circuits.QueryCircuitHistory',
        'runtime.operations.queries.circuits.handle_query_circuit_history',
        'authority.operator_decisions',
        NULL,
        NULL,
        NULL,
        TRUE,
        'binding.operation_catalog_registry.operator_finish.20260417',
        'decision.operation_catalog_registry.operator_finish.20260417'
    ),
    (
        'operator-circuit-override',
        'operator.circuit_override',
        'operation_command',
        'command',
        'POST',
        '/api/circuits',
        'runtime.operations.commands.operator_control.CircuitOverrideCommand',
        'runtime.operations.commands.operator_control.handle_circuit_override',
        'authority.operator_decisions',
        NULL,
        NULL,
        NULL,
        TRUE,
        'binding.operation_catalog_registry.operator_finish.20260417',
        'decision.operation_catalog_registry.operator_finish.20260417'
    )
ON CONFLICT (operation_ref) DO UPDATE
SET
    operation_name = EXCLUDED.operation_name,
    source_kind = EXCLUDED.source_kind,
    operation_kind = EXCLUDED.operation_kind,
    http_method = EXCLUDED.http_method,
    http_path = EXCLUDED.http_path,
    input_model_ref = EXCLUDED.input_model_ref,
    handler_ref = EXCLUDED.handler_ref,
    authority_ref = EXCLUDED.authority_ref,
    projection_ref = EXCLUDED.projection_ref,
    posture = EXCLUDED.posture,
    idempotency_policy = EXCLUDED.idempotency_policy,
    enabled = EXCLUDED.enabled,
    binding_revision = EXCLUDED.binding_revision,
    decision_ref = EXCLUDED.decision_ref,
    updated_at = now();

COMMIT;
