-- Migration 209: runtime-target neutral empty thin sandbox defaults.
--
-- The workflow worker image remains the control-plane service image. Model
-- sandboxes resolve through provider-family thin images, receive context via
-- MCP/context shards, and submit sealed outputs back to Praxis.db.

BEGIN;

UPDATE registry_sandbox_profile_authority
SET docker_image = NULL,
    docker_memory = '500m',
    workspace_materialization = 'none',
    network_policy = 'provider_only',
    auth_mount_policy = 'provider_scoped',
    recorded_at = now()
WHERE sandbox_profile_ref = 'sandbox_profile.praxis.default';

INSERT INTO registry_sandbox_profile_authority (
    sandbox_profile_ref,
    sandbox_provider,
    docker_image,
    docker_cpus,
    docker_memory,
    network_policy,
    workspace_materialization,
    secret_allowlist,
    auth_mount_policy,
    timeout_profile
) VALUES (
    'sandbox_profile.praxis.legacy_copy_debug',
    'docker_local',
    NULL,
    '2',
    '500m',
    'provider_only',
    'copy',
    '["ANTHROPIC_API_KEY","OPENAI_API_KEY","GOOGLE_API_KEY","GEMINI_API_KEY"]'::jsonb,
    'provider_scoped',
    'default'
)
ON CONFLICT (sandbox_profile_ref) DO UPDATE SET
    sandbox_provider = EXCLUDED.sandbox_provider,
    docker_image = EXCLUDED.docker_image,
    docker_cpus = EXCLUDED.docker_cpus,
    docker_memory = EXCLUDED.docker_memory,
    network_policy = EXCLUDED.network_policy,
    workspace_materialization = EXCLUDED.workspace_materialization,
    secret_allowlist = EXCLUDED.secret_allowlist,
    auth_mount_policy = EXCLUDED.auth_mount_policy,
    timeout_profile = EXCLUDED.timeout_profile,
    recorded_at = now();

INSERT INTO operation_catalog_registry (
    operation_ref,
    operation_name,
    source_kind,
    operation_kind,
    http_method,
    http_path,
    input_model_ref,
    handler_ref,
    authority_ref,
    authority_domain_ref,
    projection_ref,
    storage_target_ref,
    input_schema_ref,
    output_schema_ref,
    idempotency_key_fields,
    required_capabilities,
    allowed_callers,
    timeout_ms,
    receipt_required,
    event_required,
    event_type,
    projection_freshness_policy_ref,
    posture,
    idempotency_policy,
    enabled,
    binding_revision,
    decision_ref
) VALUES
    (
        'runtime-setup-doctor',
        'runtime.setup.doctor',
        'operation_query',
        'query',
        'GET',
        '/api/setup/doctor',
        'runtime.setup_wizard.SetupQuery',
        'runtime.setup_wizard.setup_payload',
        'authority.service_lifecycle',
        'authority.service_lifecycle',
        'projection.service_lifecycle.instances',
        'praxis.primary_postgres',
        'runtime.setup_wizard.SetupQuery',
        'runtime.setup.doctor',
        '[]'::jsonb,
        '{}'::jsonb,
        '["http","mcp","cli","website"]'::jsonb,
        15000,
        TRUE,
        FALSE,
        NULL,
        'projection_freshness.default',
        'observe',
        'read_only',
        TRUE,
        'binding.operation_catalog_registry.runtime_setup.20260422',
        'decision.runtime_setup.empty_thin_sandbox.20260422'
    ),
    (
        'runtime-setup-plan',
        'runtime.setup.plan',
        'operation_query',
        'query',
        'GET',
        '/api/setup/plan',
        'runtime.setup_wizard.SetupQuery',
        'runtime.setup_wizard.setup_payload',
        'authority.service_lifecycle',
        'authority.service_lifecycle',
        'projection.service_lifecycle.instances',
        'praxis.primary_postgres',
        'runtime.setup_wizard.SetupQuery',
        'runtime.setup.plan',
        '[]'::jsonb,
        '{}'::jsonb,
        '["http","mcp","cli","website"]'::jsonb,
        15000,
        TRUE,
        FALSE,
        NULL,
        'projection_freshness.default',
        'observe',
        'read_only',
        TRUE,
        'binding.operation_catalog_registry.runtime_setup.20260422',
        'decision.runtime_setup.empty_thin_sandbox.20260422'
    ),
    (
        'runtime-setup-apply',
        'runtime.setup.apply',
        'operation_command',
        'command',
        'POST',
        '/api/setup/apply',
        'runtime.setup_wizard.SetupApplyCommand',
        'runtime.setup_wizard.setup_payload',
        'authority.service_lifecycle',
        'authority.service_lifecycle',
        'projection.service_lifecycle.instances',
        'praxis.primary_postgres',
        'runtime.setup_wizard.SetupApplyCommand',
        'runtime.setup.apply',
        '[]'::jsonb,
        '{}'::jsonb,
        '["http","mcp","cli","website"]'::jsonb,
        15000,
        TRUE,
        TRUE,
        'runtime_setup_apply_requested',
        'projection_freshness.default',
        'operate',
        'idempotent',
        TRUE,
        'binding.operation_catalog_registry.runtime_setup.20260422',
        'decision.runtime_setup.empty_thin_sandbox.20260422'
    )
ON CONFLICT (operation_ref) DO UPDATE SET
    operation_name = EXCLUDED.operation_name,
    source_kind = EXCLUDED.source_kind,
    operation_kind = EXCLUDED.operation_kind,
    http_method = EXCLUDED.http_method,
    http_path = EXCLUDED.http_path,
    input_model_ref = EXCLUDED.input_model_ref,
    handler_ref = EXCLUDED.handler_ref,
    authority_ref = EXCLUDED.authority_ref,
    authority_domain_ref = EXCLUDED.authority_domain_ref,
    projection_ref = EXCLUDED.projection_ref,
    storage_target_ref = EXCLUDED.storage_target_ref,
    input_schema_ref = EXCLUDED.input_schema_ref,
    output_schema_ref = EXCLUDED.output_schema_ref,
    idempotency_key_fields = EXCLUDED.idempotency_key_fields,
    required_capabilities = EXCLUDED.required_capabilities,
    allowed_callers = EXCLUDED.allowed_callers,
    timeout_ms = EXCLUDED.timeout_ms,
    receipt_required = EXCLUDED.receipt_required,
    event_required = EXCLUDED.event_required,
    event_type = EXCLUDED.event_type,
    projection_freshness_policy_ref = EXCLUDED.projection_freshness_policy_ref,
    posture = EXCLUDED.posture,
    idempotency_policy = EXCLUDED.idempotency_policy,
    enabled = EXCLUDED.enabled,
    binding_revision = EXCLUDED.binding_revision,
    decision_ref = EXCLUDED.decision_ref,
    updated_at = now();

INSERT INTO operator_decisions (
    operator_decision_id,
    decision_key,
    decision_kind,
    decision_status,
    title,
    rationale,
    decided_by,
    decision_source,
    effective_from,
    effective_to,
    decided_at,
    created_at,
    updated_at,
    decision_scope_kind,
    decision_scope_ref
) VALUES (
    'operator_decision.architecture_policy.workflow_execution.empty_thin_sandbox_default',
    'architecture-policy::workflow-execution::empty-thin-sandbox-default',
    'architecture_policy',
    'decided',
    'Default model execution uses empty thin provider sandboxes',
    'Model sandboxes must not receive full repo copies by default and must not fall back to praxis-worker:latest. Runtime targets are substrate-neutral authority rows operated through API/MCP; CLI and website are clients, and SSH is only build/deploy transport for selected targets. Provider-family thin images provide the baked praxis tool, MCP context access, and sealed submission path back to Praxis.db.',
    'nate',
    'conversation',
    now(),
    NULL,
    now(),
    now(),
    now(),
    'authority_domain',
    'workflow_execution'
)
ON CONFLICT (decision_key) DO UPDATE SET
    decision_status = EXCLUDED.decision_status,
    title = EXCLUDED.title,
    rationale = EXCLUDED.rationale,
    decided_by = EXCLUDED.decided_by,
    decision_source = EXCLUDED.decision_source,
    effective_to = EXCLUDED.effective_to,
    decided_at = EXCLUDED.decided_at,
    updated_at = now(),
    decision_scope_kind = EXCLUDED.decision_scope_kind,
    decision_scope_ref = EXCLUDED.decision_scope_ref;

COMMIT;
