-- LLM-facing app experience graph.
--
-- The primary Praxis UI is Moon/dashboard/chat/run detail, not Atlas. This
-- read operation gives agents a bounded, authority-aware map of surfaces,
-- controls, relationships, and renderer file anchors without launching Vite.

INSERT INTO data_dictionary_objects (
    object_kind,
    label,
    category,
    summary,
    origin_ref,
    metadata
) VALUES (
    'operation.operator.ui_experience_graph',
    'Operator UI experience graph',
    'command',
    'Query operation exposing the Praxis app experience graph for future LLM UI work.',
    '{"migration":"213_ui_experience_graph_operator_tool.sql"}'::jsonb,
    '{"authority_domain_ref":"authority.surface_catalog","operation_kind":"query"}'::jsonb
)
ON CONFLICT (object_kind) DO UPDATE SET
    label = EXCLUDED.label,
    category = EXCLUDED.category,
    summary = EXCLUDED.summary,
    origin_ref = EXCLUDED.origin_ref,
    metadata = EXCLUDED.metadata,
    updated_at = now();

INSERT INTO authority_object_registry (
    object_ref,
    object_kind,
    object_name,
    schema_name,
    authority_domain_ref,
    data_dictionary_object_kind,
    lifecycle_status,
    write_model_kind,
    owner_ref,
    source_decision_ref,
    metadata
) VALUES (
    'operation.operator.ui_experience_graph',
    'command',
    'operator.ui_experience_graph',
    NULL,
    'authority.surface_catalog',
    'operation.operator.ui_experience_graph',
    'active',
    'read_model',
    'praxis.engine',
    'decision.ui_experience_graph.llm_operator_surface.20260424',
    '{"operation_ref":"operator-ui-experience-graph"}'::jsonb
)
ON CONFLICT (object_ref) DO UPDATE SET
    object_kind = EXCLUDED.object_kind,
    object_name = EXCLUDED.object_name,
    schema_name = EXCLUDED.schema_name,
    authority_domain_ref = EXCLUDED.authority_domain_ref,
    data_dictionary_object_kind = EXCLUDED.data_dictionary_object_kind,
    lifecycle_status = EXCLUDED.lifecycle_status,
    write_model_kind = EXCLUDED.write_model_kind,
    owner_ref = EXCLUDED.owner_ref,
    source_decision_ref = EXCLUDED.source_decision_ref,
    metadata = EXCLUDED.metadata,
    updated_at = now();

INSERT INTO operation_catalog_registry (
    operation_ref,
    operation_name,
    source_kind,
    operation_kind,
    http_method,
    http_path,
    input_model_ref,
    handler_ref,
    authority_ref,
    authority_domain_ref,
    projection_ref,
    storage_target_ref,
    input_schema_ref,
    output_schema_ref,
    idempotency_key_fields,
    required_capabilities,
    allowed_callers,
    timeout_ms,
    receipt_required,
    event_required,
    event_type,
    projection_freshness_policy_ref,
    posture,
    idempotency_policy,
    enabled,
    binding_revision,
    decision_ref
) VALUES (
    'operator-ui-experience-graph',
    'operator.ui_experience_graph',
    'operation_query',
    'query',
    'GET',
    '/api/operator/ui/experience-graph',
    'runtime.operations.queries.operator_observability.QueryUiExperienceGraph',
    'runtime.operations.queries.operator_observability.handle_query_ui_experience_graph',
    'authority.surface_catalog',
    'authority.surface_catalog',
    'projection.ui_experience_graph',
    'praxis.primary_postgres',
    'runtime.operations.queries.operator_observability.QueryUiExperienceGraph',
    'operation.output.default',
    '[]'::jsonb,
    '{}'::jsonb,
    '["http","mcp","cli","workflow"]'::jsonb,
    15000,
    TRUE,
    FALSE,
    NULL,
    'projection_freshness.default',
    'observe',
    'read_only',
    TRUE,
    'binding.operation_catalog_registry.ui_experience_graph.20260424',
    'decision.ui_experience_graph.llm_operator_surface.20260424'
)
ON CONFLICT (operation_ref) DO UPDATE SET
    operation_name = EXCLUDED.operation_name,
    source_kind = EXCLUDED.source_kind,
    operation_kind = EXCLUDED.operation_kind,
    http_method = EXCLUDED.http_method,
    http_path = EXCLUDED.http_path,
    input_model_ref = EXCLUDED.input_model_ref,
    handler_ref = EXCLUDED.handler_ref,
    authority_ref = EXCLUDED.authority_ref,
    authority_domain_ref = EXCLUDED.authority_domain_ref,
    projection_ref = EXCLUDED.projection_ref,
    storage_target_ref = EXCLUDED.storage_target_ref,
    input_schema_ref = EXCLUDED.input_schema_ref,
    output_schema_ref = EXCLUDED.output_schema_ref,
    idempotency_key_fields = EXCLUDED.idempotency_key_fields,
    required_capabilities = EXCLUDED.required_capabilities,
    allowed_callers = EXCLUDED.allowed_callers,
    timeout_ms = EXCLUDED.timeout_ms,
    receipt_required = EXCLUDED.receipt_required,
    event_required = EXCLUDED.event_required,
    event_type = EXCLUDED.event_type,
    projection_freshness_policy_ref = EXCLUDED.projection_freshness_policy_ref,
    posture = EXCLUDED.posture,
    idempotency_policy = EXCLUDED.idempotency_policy,
    enabled = EXCLUDED.enabled,
    binding_revision = EXCLUDED.binding_revision,
    decision_ref = EXCLUDED.decision_ref,
    updated_at = now();
