"""Provider execution registry surface re-exported for adapter callers."""

from __future__ import annotations

from .provider_types import ProviderAdapterContract, ProviderCLIProfile
from registry.provider_execution_registry import (
    ProviderRegistryDataError,
    ProviderRegistryError,
    ProviderRegistryLoadError,
    ProviderRegistryLoadTimeout,
    ProviderRegistrySchemaError,
    RegistryLoadStatus,
    build_command,
    default_adapter_type_for_provider,
    default_llm_adapter_type,
    default_model_for_provider,
    default_provider_slug,
    get_all_profiles,
    get_profile,
    registered_providers,
    registry_health,
    reload_from_db,
    resolve_adapter_config,
    resolve_adapter_contract,
    resolve_adapter_economics,
    resolve_api_endpoint,
    resolve_api_key_env_vars,
    resolve_api_protocol_family,
    resolve_binary,
    resolve_lane_policy,
    resolve_mcp_args_template,
    resolve_provider_from_alias,
    supports_adapter,
    supports_model_adapter,
    transport_support_report,
    validate_profiles,
)

__all__ = [
    "ProviderAdapterContract",
    "ProviderCLIProfile",
    "ProviderRegistryError",
    "ProviderRegistryLoadError",
    "ProviderRegistrySchemaError",
    "ProviderRegistryDataError",
    "ProviderRegistryLoadTimeout",
    "RegistryLoadStatus",
    "reload_from_db",
    "registry_health",
    "resolve_adapter_config",
    "get_profile",
    "get_all_profiles",
    "registered_providers",
    "resolve_provider_from_alias",
    "default_provider_slug",
    "default_llm_adapter_type",
    "default_adapter_type_for_provider",
    "default_model_for_provider",
    "resolve_adapter_economics",
    "resolve_api_endpoint",
    "resolve_api_protocol_family",
    "resolve_api_key_env_vars",
    "resolve_mcp_args_template",
    "resolve_lane_policy",
    "resolve_adapter_contract",
    "supports_adapter",
    "supports_model_adapter",
    "resolve_binary",
    "build_command",
    "validate_profiles",
    "transport_support_report",
]
