from __future__ import annotations

import runtime.operation_catalog as operation_catalog
from runtime.operation_catalog_bindings import resolve_http_operation_binding


_SEEDED_OPERATION_ROWS = [
    {
        "operation_ref": "workflow-build-mutate",
        "operation_name": "workflow_build.mutate",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/workflows/{workflow_id}/build/{subpath:path}",
        "input_model_ref": "runtime.operations.commands.workflow_build.MutateWorkflowBuildCommand",
        "handler_ref": "runtime.operations.commands.workflow_build.handle_mutate_workflow_build",
        "authority_ref": "authority.workflow_build",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.bootstrap.20260416",
        "decision_ref": "decision.operation_catalog_registry.bootstrap.20260416",
    },
    {
        "operation_ref": "workflow-build-suggest-next",
        "operation_name": "workflow_build.suggest_next",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "POST",
        "http_path": "/api/workflows/{workflow_id}/build/suggest-next",
        "input_model_ref": "runtime.operations.commands.suggest_next.SuggestNextNodesCommand",
        "handler_ref": "runtime.operations.commands.suggest_next.handle_suggest_next_nodes",
        "authority_ref": "authority.capability_catalog",
        "projection_ref": "projection.capability_catalog",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.bootstrap.20260416",
        "decision_ref": "decision.operation_catalog_registry.bootstrap.20260416",
    },
    {
        "operation_ref": "operator-roadmap-tree",
        "operation_name": "operator.roadmap_tree",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/operator/roadmap/tree/{root_roadmap_item_id}",
        "input_model_ref": "runtime.operations.queries.roadmap_tree.QueryRoadmapTree",
        "handler_ref": "runtime.operations.queries.roadmap_tree.handle_query_roadmap_tree",
        "authority_ref": "authority.roadmap_items",
        "projection_ref": "projection.roadmap_tree",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.bootstrap.20260416",
        "decision_ref": "decision.operation_catalog_registry.bootstrap.20260416",
    },
    {
        "operation_ref": "operator-data-dictionary",
        "operation_name": "operator.data_dictionary",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/operator/data-dictionary",
        "input_model_ref": "runtime.operations.queries.data_dictionary.QueryDataDictionary",
        "handler_ref": "runtime.operations.queries.data_dictionary.handle_query_data_dictionary",
        "authority_ref": "authority.memory_entities",
        "projection_ref": "projection.memory_entities",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.bootstrap.20260416",
        "decision_ref": "decision.operation_catalog_registry.bootstrap.20260416",
    },
    {
        "operation_ref": "operator-roadmap-write",
        "operation_name": "operator.roadmap_write",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/roadmap-write",
        "input_model_ref": "runtime.operations.commands.operator_control.RoadmapWriteCommand",
        "handler_ref": "runtime.operations.commands.operator_control.handle_operator_roadmap_write",
        "authority_ref": "authority.roadmap_items",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.operator_control_bindings.20260416",
        "decision_ref": "decision.operation_catalog_registry.operator_control_bindings.20260416",
    },
    {
        "operation_ref": "operator-work-item-closeout",
        "operation_name": "operator.work_item_closeout",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/work-item-closeout",
        "input_model_ref": "runtime.operations.commands.operator_control.WorkItemCloseoutCommand",
        "handler_ref": "runtime.operations.commands.operator_control.handle_work_item_closeout",
        "authority_ref": "authority.work_item_closeout",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.operator_control_bindings.20260416",
        "decision_ref": "decision.operation_catalog_registry.operator_control_bindings.20260416",
    },
    {
        "operation_ref": "operator-task-route-eligibility",
        "operation_name": "operator.task_route_eligibility",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/task-route-eligibility",
        "input_model_ref": "runtime.operations.commands.operator_control.TaskRouteEligibilityCommand",
        "handler_ref": "runtime.operations.commands.operator_control.handle_task_route_eligibility",
        "authority_ref": "authority.task_route_eligibility",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.surface_cleanup.20260416",
        "decision_ref": "decision.operation_catalog_registry.surface_cleanup.20260416",
    },
    {
        "operation_ref": "operator-native-primary-cutover-gate",
        "operation_name": "operator.native_primary_cutover_gate",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/native-primary-cutover-gate",
        "input_model_ref": "runtime.operations.commands.operator_control.NativePrimaryCutoverGateCommand",
        "handler_ref": "runtime.operations.commands.operator_control.handle_native_primary_cutover_gate",
        "authority_ref": "authority.native_primary_cutover_gate",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.surface_cleanup.20260416",
        "decision_ref": "decision.operation_catalog_registry.surface_cleanup.20260416",
    },
    {
        "operation_ref": "operator-transport-support",
        "operation_name": "operator.transport_support",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "POST",
        "http_path": "/api/operator/transport-support",
        "input_model_ref": "runtime.operations.queries.operator_support.QueryTransportSupport",
        "handler_ref": "runtime.operations.queries.operator_support.handle_query_transport_support",
        "authority_ref": "authority.transport_eligibility",
        "projection_ref": "projection.transport_eligibility",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.surface_cleanup.20260416",
        "decision_ref": "decision.operation_catalog_registry.surface_cleanup.20260416",
    },
    {
        "operation_ref": "operator-provider-onboarding",
        "operation_name": "operator.provider_onboarding",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/provider-onboarding",
        "input_model_ref": "runtime.operations.commands.provider_onboarding.ProviderOnboardingCommand",
        "handler_ref": "runtime.operations.commands.provider_onboarding.handle_provider_onboarding",
        "authority_ref": "authority.provider_onboarding",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.provider_onboarding.20260416",
        "decision_ref": "decision.operation_catalog_registry.provider_onboarding.20260416",
    },
    {
        "operation_ref": "operator-decision-record",
        "operation_name": "operator.decision_record",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/decision",
        "input_model_ref": "runtime.operations.commands.operator_control.OperatorDecisionRecordCommand",
        "handler_ref": "runtime.operations.commands.operator_control.handle_operator_decision_record",
        "authority_ref": "authority.operator_decisions",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.operator_decision_bindings.20260417",
        "decision_ref": "decision.operation_catalog_registry.operator_decision_bindings.20260417",
    },
    {
        "operation_ref": "operator-decision-list",
        "operation_name": "operator.decision_list",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/operator/decisions",
        "input_model_ref": "runtime.operations.queries.operator_decisions.QueryOperatorDecisions",
        "handler_ref": "runtime.operations.queries.operator_decisions.handle_query_operator_decisions",
        "authority_ref": "authority.operator_decisions",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.operator_decision_bindings.20260417",
        "decision_ref": "decision.operation_catalog_registry.operator_decision_bindings.20260417",
    },
    {
        "operation_ref": "operator-architecture-policy-record",
        "operation_name": "operator.architecture_policy_record",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/architecture-policy",
        "input_model_ref": "runtime.operations.commands.operator_control.ArchitecturePolicyRecordCommand",
        "handler_ref": "runtime.operations.commands.operator_control.handle_architecture_policy_record",
        "authority_ref": "authority.operator_decisions",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.operator_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.operator_finish.20260417",
    },
    {
        "operation_ref": "operator-functional-area-record",
        "operation_name": "operator.functional_area_record",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/functional-area",
        "input_model_ref": "runtime.operations.commands.operator_control.FunctionalAreaRecordCommand",
        "handler_ref": "runtime.operations.commands.operator_control.handle_functional_area_record",
        "authority_ref": "authority.functional_areas",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.operator_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.operator_finish.20260417",
    },
    {
        "operation_ref": "operator-object-relation-record",
        "operation_name": "operator.object_relation_record",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/object-relation",
        "input_model_ref": "runtime.operations.commands.operator_control.OperatorObjectRelationRecordCommand",
        "handler_ref": "runtime.operations.commands.operator_control.handle_operator_object_relation_record",
        "authority_ref": "authority.operator_object_relations",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.operator_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.operator_finish.20260417",
    },
    {
        "operation_ref": "operator-circuit-states",
        "operation_name": "operator.circuit_states",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/circuits",
        "input_model_ref": "runtime.operations.queries.circuits.QueryCircuitStates",
        "handler_ref": "runtime.operations.queries.circuits.handle_query_circuit_states",
        "authority_ref": "authority.circuit_breakers",
        "projection_ref": "projection.circuit_breakers",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.operator_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.operator_finish.20260417",
    },
    {
        "operation_ref": "operator-circuit-history",
        "operation_name": "operator.circuit_history",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/circuits/history",
        "input_model_ref": "runtime.operations.queries.circuits.QueryCircuitHistory",
        "handler_ref": "runtime.operations.queries.circuits.handle_query_circuit_history",
        "authority_ref": "authority.operator_decisions",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.operator_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.operator_finish.20260417",
    },
    {
        "operation_ref": "operator-circuit-override",
        "operation_name": "operator.circuit_override",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/circuits",
        "input_model_ref": "runtime.operations.commands.operator_control.CircuitOverrideCommand",
        "handler_ref": "runtime.operations.commands.operator_control.handle_circuit_override",
        "authority_ref": "authority.operator_decisions",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.operator_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.operator_finish.20260417",
    },
    {
        "operation_ref": "operator-status-snapshot",
        "operation_name": "operator.status_snapshot",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/status",
        "input_model_ref": "runtime.operations.queries.operator_observability.QueryOperatorStatusSnapshot",
        "handler_ref": "runtime.operations.queries.operator_observability.handle_query_operator_status_snapshot",
        "authority_ref": "authority.receipts",
        "projection_ref": "projection.receipts",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.observability_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.observability_finish.20260417",
    },
    {
        "operation_ref": "operator-issue-backlog",
        "operation_name": "operator.issue_backlog",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/operator/issue-backlog",
        "input_model_ref": "runtime.operations.queries.operator_observability.QueryOperatorIssueBacklog",
        "handler_ref": "runtime.operations.queries.operator_observability.handle_query_operator_issue_backlog",
        "authority_ref": "authority.operator_issues",
        "projection_ref": "projection.operator_issues",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.observability_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.observability_finish.20260417",
    },
    {
        "operation_ref": "operator-ideas",
        "operation_name": "operator.ideas",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/ideas",
        "input_model_ref": "runtime.operations.commands.operator_control.OperatorIdeasCommand",
        "handler_ref": "runtime.operations.commands.operator_control.handle_operator_ideas",
        "authority_ref": "authority.operator_ideas",
        "projection_ref": "projection.operator_ideas",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.operator_ideas.20260421",
        "decision_ref": "architecture-policy::operator-ideas::ideas-are-pre-commitment-roadmap-is-commitment",
    },
    {
        "operation_ref": "operator-replay-ready-bugs",
        "operation_name": "operator.replay_ready_bugs",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/operator/replay-ready-bugs",
        "input_model_ref": "runtime.operations.queries.operator_observability.QueryReplayReadyBugs",
        "handler_ref": "runtime.operations.queries.operator_observability.handle_query_replay_ready_bugs",
        "authority_ref": "authority.bugs",
        "projection_ref": "projection.bugs",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.observability_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.observability_finish.20260417",
    },
    {
        "operation_ref": "operator-graph-projection",
        "operation_name": "operator.graph_projection",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/operator/graph",
        "input_model_ref": "runtime.operations.queries.operator_observability.QueryOperatorGraphProjection",
        "handler_ref": "runtime.operations.queries.operator_observability.handle_query_operator_graph_projection",
        "authority_ref": "authority.semantic_assertions",
        "projection_ref": "projection.operator_graph",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.observability_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.observability_finish.20260417",
    },
    {
        "operation_ref": "operator-run-status",
        "operation_name": "operator.run_status",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/operator/runs/{run_id}/status",
        "input_model_ref": "runtime.operations.queries.operator_observability.QueryRunScopedOperatorView",
        "handler_ref": "runtime.operations.queries.operator_observability.handle_query_run_status_view",
        "authority_ref": "authority.workflow_runs",
        "projection_ref": "projection.operator_status",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.observability_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.observability_finish.20260417",
    },
    {
        "operation_ref": "operator-run-scoreboard",
        "operation_name": "operator.run_scoreboard",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/operator/runs/{run_id}/scoreboard",
        "input_model_ref": "runtime.operations.queries.operator_observability.QueryRunScopedOperatorView",
        "handler_ref": "runtime.operations.queries.operator_observability.handle_query_run_scoreboard_view",
        "authority_ref": "authority.workflow_runs",
        "projection_ref": "projection.operator_scoreboard",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.observability_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.observability_finish.20260417",
    },
    {
        "operation_ref": "operator-run-graph",
        "operation_name": "operator.run_graph",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/operator/runs/{run_id}/graph",
        "input_model_ref": "runtime.operations.queries.operator_observability.QueryRunScopedOperatorView",
        "handler_ref": "runtime.operations.queries.operator_observability.handle_query_run_graph_view",
        "authority_ref": "authority.workflow_runs",
        "projection_ref": "projection.workflow_graph",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.observability_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.observability_finish.20260417",
    },
    {
        "operation_ref": "operator-run-lineage",
        "operation_name": "operator.run_lineage",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/operator/runs/{run_id}/lineage",
        "input_model_ref": "runtime.operations.queries.operator_observability.QueryRunScopedOperatorView",
        "handler_ref": "runtime.operations.queries.operator_observability.handle_query_run_lineage_view",
        "authority_ref": "authority.workflow_runs",
        "projection_ref": "projection.workflow_lineage",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.observability_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.observability_finish.20260417",
    },
    {
        "operation_ref": "operator-metrics-reset",
        "operation_name": "operator.metrics_reset",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/maintenance/reset-metrics",
        "input_model_ref": "runtime.operations.commands.operator_maintenance.ResetMetricsCommand",
        "handler_ref": "runtime.operations.commands.operator_maintenance.handle_reset_metrics",
        "authority_ref": "authority.observability_metrics",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.observability_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.observability_finish.20260417",
    },
    {
        "operation_ref": "operator-bug-replay-provenance-backfill",
        "operation_name": "operator.bug_replay_provenance_backfill",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/maintenance/backfill-bug-replay-provenance",
        "input_model_ref": "runtime.operations.commands.operator_maintenance.BackfillBugReplayProvenanceCommand",
        "handler_ref": "runtime.operations.commands.operator_maintenance.handle_backfill_bug_replay_provenance",
        "authority_ref": "authority.bugs",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.observability_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.observability_finish.20260417",
    },
    {
        "operation_ref": "operator-semantic-bridges-backfill",
        "operation_name": "operator.semantic_bridges_backfill",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/maintenance/backfill-semantic-bridges",
        "input_model_ref": "runtime.operations.commands.operator_maintenance.BackfillSemanticBridgesCommand",
        "handler_ref": "runtime.operations.commands.operator_maintenance.handle_backfill_semantic_bridges",
        "authority_ref": "authority.semantic_assertions",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.observability_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.observability_finish.20260417",
    },
    {
        "operation_ref": "operator-semantic-projection-refresh",
        "operation_name": "operator.semantic_projection_refresh",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/operator/maintenance/refresh-semantic-projection",
        "input_model_ref": "runtime.operations.commands.operator_maintenance.RefreshSemanticProjectionCommand",
        "handler_ref": "runtime.operations.commands.operator_maintenance.handle_refresh_semantic_projection",
        "authority_ref": "authority.semantic_assertions",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.observability_finish.20260417",
        "decision_ref": "decision.operation_catalog_registry.observability_finish.20260417",
    },
    {
        "operation_ref": "object-schema-type-list",
        "operation_name": "object_schema.type_list",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/object-types",
        "input_model_ref": "runtime.operations.queries.object_schema.QueryObjectTypes",
        "handler_ref": "runtime.operations.queries.object_schema.handle_query_object_types",
        "authority_ref": "authority.object_schema",
        "projection_ref": "projection.object_schema",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.object_schema_bindings.20260417",
        "decision_ref": "decision.operation_catalog_registry.object_schema_bindings.20260417",
    },
    {
        "operation_ref": "object-schema-type-get",
        "operation_name": "object_schema.type_get",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/object-types/{type_id}",
        "input_model_ref": "runtime.operations.queries.object_schema.QueryObjectType",
        "handler_ref": "runtime.operations.queries.object_schema.handle_query_object_type",
        "authority_ref": "authority.object_schema",
        "projection_ref": "projection.object_schema",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.object_schema_bindings.20260417",
        "decision_ref": "decision.operation_catalog_registry.object_schema_bindings.20260417",
    },
    {
        "operation_ref": "object-schema-type-upsert-post",
        "operation_name": "object_schema.type_upsert",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/object-types",
        "input_model_ref": "runtime.operations.commands.object_schema.UpsertObjectTypeCommand",
        "handler_ref": "runtime.operations.commands.object_schema.handle_upsert_object_type",
        "authority_ref": "authority.object_schema",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.object_schema_bindings.20260417",
        "decision_ref": "decision.operation_catalog_registry.object_schema_bindings.20260417",
    },
    {
        "operation_ref": "object-schema-type-upsert-put",
        "operation_name": "object_schema.type_upsert_by_id",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "PUT",
        "http_path": "/api/object-types/{type_id}",
        "input_model_ref": "runtime.operations.commands.object_schema.UpsertObjectTypeCommand",
        "handler_ref": "runtime.operations.commands.object_schema.handle_upsert_object_type",
        "authority_ref": "authority.object_schema",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.object_schema_bindings.20260417",
        "decision_ref": "decision.operation_catalog_registry.object_schema_bindings.20260417",
    },
    {
        "operation_ref": "object-schema-type-delete",
        "operation_name": "object_schema.type_delete",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "DELETE",
        "http_path": "/api/object-types/{type_id}",
        "input_model_ref": "runtime.operations.commands.object_schema.DeleteObjectTypeCommand",
        "handler_ref": "runtime.operations.commands.object_schema.handle_delete_object_type",
        "authority_ref": "authority.object_schema",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.object_schema_bindings.20260417",
        "decision_ref": "decision.operation_catalog_registry.object_schema_bindings.20260417",
    },
    {
        "operation_ref": "object-schema-field-list",
        "operation_name": "object_schema.field_list",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/object-types/{type_id}/fields",
        "input_model_ref": "runtime.operations.queries.object_schema.QueryObjectFields",
        "handler_ref": "runtime.operations.queries.object_schema.handle_query_object_fields",
        "authority_ref": "authority.object_schema",
        "projection_ref": "projection.object_schema",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.object_schema_bindings.20260417",
        "decision_ref": "decision.operation_catalog_registry.object_schema_bindings.20260417",
    },
    {
        "operation_ref": "object-schema-field-upsert",
        "operation_name": "object_schema.field_upsert",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/object-types/{type_id}/fields",
        "input_model_ref": "runtime.operations.commands.object_schema.UpsertObjectFieldCommand",
        "handler_ref": "runtime.operations.commands.object_schema.handle_upsert_object_field",
        "authority_ref": "authority.object_schema",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.object_schema_bindings.20260417",
        "decision_ref": "decision.operation_catalog_registry.object_schema_bindings.20260417",
    },
    {
        "operation_ref": "object-schema-field-retire",
        "operation_name": "object_schema.field_retire",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "DELETE",
        "http_path": "/api/object-types/{type_id}/fields/{field_name}",
        "input_model_ref": "runtime.operations.commands.object_schema.RetireObjectFieldCommand",
        "handler_ref": "runtime.operations.commands.object_schema.handle_retire_object_field",
        "authority_ref": "authority.object_schema",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.object_schema_bindings.20260417",
        "decision_ref": "decision.operation_catalog_registry.object_schema_bindings.20260417",
    },
    {
        "operation_ref": "semantic-assertion-register-predicate",
        "operation_name": "semantic_assertions.register_predicate",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/semantic/predicate",
        "input_model_ref": "runtime.operations.commands.semantic_assertions.RegisterSemanticPredicateCommand",
        "handler_ref": "runtime.operations.commands.semantic_assertions.handle_register_semantic_predicate",
        "authority_ref": "authority.semantic_predicates",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.semantic_assertions.20260416",
        "decision_ref": "decision.operation_catalog_registry.semantic_assertions.20260416",
    },
    {
        "operation_ref": "semantic-assertion-record",
        "operation_name": "semantic_assertions.record",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/semantic/assertion",
        "input_model_ref": "runtime.operations.commands.semantic_assertions.RecordSemanticAssertionCommand",
        "handler_ref": "runtime.operations.commands.semantic_assertions.handle_record_semantic_assertion",
        "authority_ref": "authority.semantic_assertions",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.semantic_assertions.20260416",
        "decision_ref": "decision.operation_catalog_registry.semantic_assertions.20260416",
    },
    {
        "operation_ref": "semantic-assertion-retract",
        "operation_name": "semantic_assertions.retract",
        "source_kind": "operation_command",
        "operation_kind": "command",
        "http_method": "POST",
        "http_path": "/api/semantic/assertion/retract",
        "input_model_ref": "runtime.operations.commands.semantic_assertions.RetractSemanticAssertionCommand",
        "handler_ref": "runtime.operations.commands.semantic_assertions.handle_retract_semantic_assertion",
        "authority_ref": "authority.semantic_assertions",
        "projection_ref": None,
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.semantic_assertions.20260416",
        "decision_ref": "decision.operation_catalog_registry.semantic_assertions.20260416",
    },
    {
        "operation_ref": "semantic-assertion-list",
        "operation_name": "semantic_assertions.list",
        "source_kind": "operation_query",
        "operation_kind": "query",
        "http_method": "GET",
        "http_path": "/api/semantic/assertions",
        "input_model_ref": "runtime.operations.queries.semantic_assertions.QuerySemanticAssertions",
        "handler_ref": "runtime.operations.queries.semantic_assertions.handle_query_semantic_assertions",
        "authority_ref": "authority.semantic_assertions",
        "projection_ref": "projection.semantic_current_assertions",
        "posture": None,
        "idempotency_policy": None,
        "enabled": True,
        "binding_revision": "binding.operation_catalog_registry.semantic_assertions.20260416",
        "decision_ref": "decision.operation_catalog_registry.semantic_assertions.20260416",
    },
]

_SEEDED_SOURCE_POLICIES = [
    {
        "policy_ref": "operation-command",
        "source_kind": "operation_command",
        "posture": "operate",
        "idempotency_policy": "non_idempotent",
        "enabled": True,
        "binding_revision": "binding.operation_catalog_source_policy_registry.bootstrap.20260416",
        "decision_ref": "decision.operation_catalog_source_policy_registry.bootstrap.20260416",
    },
    {
        "policy_ref": "operation-query",
        "source_kind": "operation_query",
        "posture": "observe",
        "idempotency_policy": "read_only",
        "enabled": True,
        "binding_revision": "binding.operation_catalog_source_policy_registry.bootstrap.20260416",
        "decision_ref": "decision.operation_catalog_source_policy_registry.bootstrap.20260416",
    },
]


def test_seeded_operation_catalog_rows_resolve_to_live_bindings(monkeypatch) -> None:
    monkeypatch.setattr(
        operation_catalog,
        "_list_operation_catalog_records",
        lambda conn, source_kind=None, include_disabled=False, limit=100: list(
            _SEEDED_OPERATION_ROWS
        ),
    )
    monkeypatch.setattr(
        operation_catalog,
        "_list_operation_source_policy_records",
        lambda conn, include_disabled=False, limit=100: list(_SEEDED_SOURCE_POLICIES),
    )

    seeded = {
        item.operation_name: item
        for item in operation_catalog.list_resolved_operation_definitions(
            object(),
            include_disabled=True,
        )
    }

    assert set(seeded) == {
        "workflow_build.mutate",
        "workflow_build.suggest_next",
        "operator.roadmap_tree",
        "operator.data_dictionary",
        "operator.roadmap_write",
        "operator.work_item_closeout",
        "operator.task_route_eligibility",
        "operator.native_primary_cutover_gate",
        "operator.transport_support",
        "operator.provider_onboarding",
        "operator.decision_record",
        "operator.decision_list",
        "operator.architecture_policy_record",
        "operator.functional_area_record",
        "operator.object_relation_record",
        "operator.circuit_states",
        "operator.circuit_history",
        "operator.circuit_override",
        "operator.status_snapshot",
        "operator.issue_backlog",
        "operator.ideas",
        "operator.replay_ready_bugs",
        "operator.graph_projection",
        "operator.run_status",
        "operator.run_scoreboard",
        "operator.run_graph",
        "operator.run_lineage",
        "operator.metrics_reset",
        "operator.bug_replay_provenance_backfill",
        "operator.semantic_bridges_backfill",
        "operator.semantic_projection_refresh",
        "object_schema.type_list",
        "object_schema.type_get",
        "object_schema.type_upsert",
        "object_schema.type_upsert_by_id",
        "object_schema.type_delete",
        "object_schema.field_list",
        "object_schema.field_upsert",
        "object_schema.field_retire",
        "semantic_assertions.register_predicate",
        "semantic_assertions.record",
        "semantic_assertions.retract",
        "semantic_assertions.list",
    }

    signatures: set[tuple[str, str]] = set()
    for resolved in seeded.values():
        binding = resolve_http_operation_binding(resolved)
        assert binding.operation_name == resolved.operation_name
        assert callable(binding.handler)
        signatures.add((binding.http_method, binding.http_path))

    assert len(signatures) == len(seeded)
