from __future__ import annotations

import json
from pathlib import Path
from pprint import pformat

_POLICY_ORDER = ("canonical", "bootstrap_only", "deprecated", "dead")


def main() -> None:
    workflow_root = Path(__file__).resolve().parents[1]
    spec_path = workflow_root / "system_authority" / "workflow_migration_authority.json"
    output_path = workflow_root / "storage" / "_generated_workflow_migration_authority.py"

    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    policy_buckets = {
        policy: tuple(spec["policy_buckets"].get(policy, ())) for policy in _POLICY_ORDER
    }
    manifest = tuple(spec["canonical_manifest"])
    full_bootstrap = tuple(
        sorted(set(policy_buckets["canonical"]) | set(policy_buckets["bootstrap_only"]))
    )
    expected_objects = {
        filename: tuple(
            (str(item["object_type"]), str(item["object_name"]))
            for item in objects
        )
        for filename, objects in spec["expected_objects"].items()
    }
    readiness_sequence = tuple(
        (filename, expected_objects[filename]) for filename in manifest
    )
    migration_policies = {
        filename: policy
        for policy, filenames in policy_buckets.items()
        for filename in filenames
    }

    generated = "\n".join(
        [
            '"""Generated workflow migration authority artifacts.\n\nDo not edit this file directly. Update\n`system_authority/workflow_migration_authority.json` and regenerate instead.\n"""',
            "",
            "from __future__ import annotations",
            "",
            "WORKFLOW_MIGRATION_SEQUENCE = " + pformat(manifest, width=88, sort_dicts=False),
            "",
            "WORKFLOW_FULL_BOOTSTRAP_SEQUENCE = "
            + pformat(full_bootstrap, width=88, sort_dicts=False),
            "",
            "WORKFLOW_POLICY_BUCKETS = "
            + pformat(policy_buckets, width=88, sort_dicts=False),
            "",
            "WORKFLOW_MIGRATION_POLICIES = "
            + pformat(migration_policies, width=88, sort_dicts=False),
            "",
            "WORKFLOW_MIGRATION_EXPECTED_OBJECTS = "
            + pformat(expected_objects, width=88, sort_dicts=False),
            "",
            "WORKFLOW_SCHEMA_READINESS_SEQUENCE = "
            + pformat(readiness_sequence, width=88, sort_dicts=False),
            "",
        ]
    )
    output_path.write_text(generated + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
